### PR TITLE
Initial matinee support to control facial animations on actors

### PR DESCRIPTION
**Pull request by oliverzx**
- Added FaceFX Matinee Track using key frames that can be assigned to specific skelmesh components in the owning actor
- Added support for specific audio component to be assigned when setting up the FaceFX component (for parallel audio playback of facial animation on different skelmesh components)
- Matinee keyframes support animation specification by id (existing or arbitrary) and by asset selection

### CODE REVIEW

**Comment by dpakatheman** [comment]
As we spoke about on Skype, you can get into a state where the FaceFX Matinee track is not attached to an actor with a FaceFX Component.  I see that we try to defend against this state when you have an object selected that doesn't have a FaceFX Component.  Trying to add a FaceFX Matinee track gives you a toaster message: "Unable to add FaceFX Track.  Selected actor does not have a FaceFX Component."

But if you have *nothing* selected when you create your Matinee track group (you can easily get into this state by clicking on an empty portion of the matinee tracks view), you can add a FaceFX Track to that group without seeing a toaster message.  Then when you try to add a key to the FaceFX track, nothing happens, but there is a Log warning "LogFaceFX:Warning: No Actor is selected. Select actor first"

Is it possible to display a toaster message when you try to add the FaceFX track if the group is not attached to any actor?

**Comment by dpakatheman** [comment]
I'm getting into a strange state using FaceFX tracks in Matinee where the audio for a FaceFX animation is always played on level start (the mouth doesn't move, but the audio plays).  The matinee doesn't need to be triggered for the audio to be played in this way.  I can delete the matinee actor and the state persists.  Only when I delete the audio component from the actor's blueprint, and re-add a new audio component does the problem fix itself.

I get into this state by adding a FaceFX Track in Matinee, and adding a key to play a FaceFX animation with audio.  Then I hit play from the Matinee tab, and let the matinee play until the FaceFX animation is fired.  From that point on, I can't start the level without hearing the audio.

**Comment by oliverzx** [comment]
> Is it possible to display a toaster message when you try to add the FaceFX track if the group is not attached to any actor?

Sure...i can add that.

Regarding the state, that sounds like a persistence issue with the audio component state...will check

**Comment by dpakatheman** [comment]
After a FaceFX animation fired from a Matinee track is completed, log errors are spewed that look like:  UFaceFXCharacter::JumpTo.  Invalid position range.  Value: X.XX, Asset: XXX

I think this is a known issue and is related to the discussion you had with Jamie, but FYI

image

**Comment by oliverzx** [comment]
Yeah that should be caused by the missing ramp up consideration...thanks

**Comment by oliverzx** [comment]
So i fixed some issues and add your toaster messages. Shall i close this one and send you an updated pull request or do you want to continue discussing here before that ?

**Comment by jcredmond** [comment]
You can always fix it in here and then rebase with upstream and squash it all into one commit, if you know how to do that. IIRC you don't use the git command line, so it will definitely be easier for you to trash this one and create a new one, but as you pointed out we will lost all the commentary here when you do that.

**Comment by oliverzx** [comment]
The fixed are added to this pull request. I keep it open for discussion. When its all fine i'll create a new one with all changes...

**Comment by dpakatheman** [comment]
The latest resolves all of the issues I have found so far.

**Comment by dpakatheman** [comment]
There are some issues with how Matinee deals with incompatible FaceFX animations.  

1)   I agree that we need to alert the user if they try to play an incompatible animation in matinee, but we currently do it with a toaster message on every tick and it seems a bit overkill:

image


2) Once you correct the issue (do a rebuild/reimport all), you can play the Matinee from game, but if I scrub the matinee timeline or play from matinee, I get a toaster message for every tick telling me the animations are incompatible, even though the animations/actor is up to date.  I can't seem to get out of this state without deleting the instance of the blueprint class in the scene, adding a new one, then generating new matinee tracks for it.  So I don't think there is any way to update an animation or actor once you have added it to Matinee.

**Comment by dpakatheman** [comment]
I'm also seeing a *really strange* issue where the proposal 001 audio refuses to play from Matinee (the animation plays without it).   The audio has no problem playing via the play node in a blueprint, and I don't have any problems with other audio have brought in.  

Is this reproducible on another machine?

**Comment by oliverzx** [comment]
Hey Doug,

yeah those messages are because of how matinee is scrubbing. I can fix that in some way...
Can you send me the assets for both problems ?

Cheers,
Oliver

**Comment by oliverzx** [comment]
Ok, i fixed those two issues. The error message spam prevention is a bit hacky though. Does its job...not sure how we could handle it better. Check the change...

**Comment by dpakatheman** [comment]
I can still reproduce the second matinee issue (#2 in the post with the screenshot above).  If I change my face graph, do a rebuild all/reimport all, Matinee will forever complain that the animations are incompatible with the actor.  The animations play fine from the game, but you get toaster messages in the Matinee tab if you try to import an animation, and the animations won't play in the matinee tab.

**Comment by oliverzx** [comment]
Can you send me the assets ?

**Comment by dpakatheman** [comment]
I'm not sure how to wrap up the assets, want to skype me when you can?  

The reproduction is easy.  Just create a matinee then update your actor's face graph with a new node.  Works in game, not from matinee tab.

**Comment by oliverzx** [comment]
Ok i couldn't really repro any issue with having matinee open and reimporting assets with invalid data but i added some handling for that which should cover that case anyway. Please have a look and check if you still see those issues on your end. Thanks

**Comment by dpakatheman** [comment]
I can still reproduce the issue.  It is not an edge case involving invalid data.  Once you create a Matinee, you can't update your FaceFX actor without losing your work in Matinee.  

Please confirm if you can not reproduce this. 

1) Create a FaceFX track in Matinee so that it plays a FaceFX animation when you start the level.
2) From FaceFX Studio, add a node to your Face Graph, and do a Rebuild All from the FaceFX Runtime Plugin.
3) In UE4, right click on the FaceFX Studio Actor and select "Reimport FaceFX Studio Assets"
4) Try to play the Matinee from the Matinee window.  The animation won't play and you get "FaceFX animation XXX is incompatible..." message.  If the animation still plays from PIE, it is only temporary.  After saving, closing and reopening UE4 the animation won't play there either and you will get the incompatible message.

**Comment by oliverzx** [comment]
I was able to repro it. It was caused by missing actor handle invalidation during actor reimport. Should be fixed now...cheers

**Comment by dpakatheman** [comment]
Nice.  Confirmed Fixed.  Getting close.

Do we need to support having multiple FaceFX Tracks in a single group?  I don't see the need and there are some issues that only show up with multiple FaceFX tracks:

1) FaceFX animation doesn't play if it isn't in the most recently added trak
2) Audio seems to get distorted if there are multiple FaceFX tracks

**Comment by oliverzx** [comment]
yeah indeed there are potential issues with that...i also don't assume we need this for now as we only support one animation per character playing at the same time anyway. Shall i limit it to one track only ?

**Comment by dpakatheman** [comment]
Yes, I think that is best.

**Comment by oliverzx** [comment]
Done...

**Comment by dpakatheman** [comment]
I'm not having any problems with PIE, and the integration is working well there.  But playing from the Matinee tab does not always work.  I think the easiest way to reproduce is:

1) Setup a new scene with a FaceFX matinee track that plays on level load.
2) Save everything and close UE4.
3) Launch UE4 and open your saved scene, and try to play from Matinee.  The Audio can be heard, but the FaceFX animation does not play from the Matinee tab (PIE still works). 

I haven't found an easy way to fix the above issue. 

Another potentially related issue is that in a newly setup scene, the Matinee tab will not play FaceFX animations or audio until you have triggered PIE once.  This one is not a big deal, but it can be temporarily confusing/inconvenient.

**Comment by oliverzx** [comment]
OK will have a look...thanks

**Comment by dpakatheman** [comment]
Just to clarify with more clear reproduction steps ( I haven't succeeded in not reproducing this yet).  I am using the sample content:
https://unreal.facefx.com/FaceFX-UE4-Sample-Content.zip

This is the order I do the setup in: 

1) Drag on FBX
2) Drag on .facefx
3) Setup anim blueprint
4) Setup blueprint  class (there is no Play FaceFX node because we will play from Matinee)
5) Drag Slade's Blueprint onto Scene
6) Setup the Matinee to play the-proposal-001-chubukov, and play on level start
7) Try to Play in Matinee (get no audio, no animation)
8) Close Matinee, then PIE ( get audio & animation)
9) File->Save All (save map as Untitled)
10) Close & reopen UE4 and map.
11) Open Matinee tab, play.  (audio, no animation).

I don't see anything in the log at this point, but I do get one error consistently if I play from Matinee, then close Matinee, click PIE and stop before the audio has finished.  I see this:

LogFaceFX:Error" UFaceFXCharacter::StopAudio.  Stopping audio failed.  Owning UFaceFXComponent does not belong to an actor that owns an UAudioComponent.  Actor. None.

I can PIE, then Stop and PIE and stop multiple times with no error, but as soon as I play from Matinee, then PIE, then stop I get that error.

**Comment by oliverzx** [comment]
Hey Doug,

issue was caused by FaceFX components which were not registered before the FaceFX blend node was initialized. Fixed that...works for me now. Please have a test on your end as well.

Cheers

**Comment by dpakatheman** [comment]
I can still reproduce this, but it is slightly more difficult.  I do the same reproduction steps 1-9 above, and then I add a second blueprint class for slade that references the original animation blueprint.  I add the second slade to the map, give him a FaceFx matinee track, and add an animation to it.  When playing in matinee, the second slade will not play. 

There does appear to be some randomness to this, or I may not have figured out the exact repo steps.  If the second slade works, I add a third slade (with a new blueprint class, but the same animation blueprint), and at that point I've normally reproduced this.

**Comment by dpakatheman** [comment]
Also, I noticed that if I select two versions of slade in the map, I can create a matinee group and add a FaceFX track to it that won't work.  Can we prevent you from adding a FaceFX track unless there is exactly one actor selected, and that actor has a facefx component?

**Comment by dpakatheman** [comment]
3rd and finally, whenever I add a new blueprint class for slade, add him to the map, and create a facefx matinee track for him, I must perform a PIE operation before playing in matinee.  Trying to immediately play in matinee before PIE results in lots of LogFaceFX:Error messages in the log (Stop/JumpTo.  Facefx character does not exist gfor the given SkelMeshComp <None>)

**Comment by dpakatheman** [comment]
the 1st and 3rd issues are related to the blueprint class not being compiled.  Even after a PIE event, you can run into the first issue, but compiling the blueprint or saving and reloading the map will fix it.  In documentation/troubleshooting, we just need to tell people to compile their blueprints if matinee does not play but PIE does.

So the second issue is the only one outstanding.  We need to prevent adding a FaceFX track to matinee groups representing more than one actor.

**Comment by oliverzx** [comment]
Added the error message...

**Pull request closed without merging**
